development:
  cloud_name: zepri
  api_key: '677669942251319'
  api_secret: IhivTAxFTzdo6XDCA_E_4WnR-EI
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: zepri
  api_key: '677669942251319'
  api_secret: IhivTAxFTzdo6XDCA_E_4WnR-EI
  enhance_image_tag: true
  static_image_support: true